<div id="strlist">
    <div class="strecord">
    <div class="theme">Панель управления</div>
        <center><p>Доступ к странице запрещён</p>
        <p><a href="<?php echo $this->url(array('module' => 'default',
                                                'controller' => 'auth',
                                                'action' => 'login'), 'login');
                    ?>">Пройдите процедуру авторизации</a>
        </p></center>
    </div>
</div>