<?php $this->headTitle('Панель управления'); ?>

<div id="strlist">
    <div class="strecord">
        <div class="theme">Панель управления</div>
        <p><ul>
            <li><a href="<?php echo $this->url(array(), 'topicControl', TRUE);
                         ?>">Управление записями</a></li>
            <?php if ($this->edit) { ?><li><a href="<?php echo $this->url(array(), 'categoryControl', TRUE);
                         ?>">Управление категориями</a></li>
            <li><a href="<?php echo $this->url(array(), 'tagsControl', TRUE);
                         ?>">Управление тегами</a></li><?php } ?>
            <?php if ($this->editUser) { ?><li><a href="<?php
                               echo $this->url(array(), 'usersControl', TRUE);
                         ?>">Управление пользователями</a></li><?php } ?>
        </ul></p>
    </div>
</div>

