<?php $this->headTitle('Удаление тега'); ?>

<div id="strlist">
    <div class="strecord">
        <div class="theme">Удаление тега</div>
        <p>Вы действительно хотите удалить тег &laquo;<?php echo $this->tag->name; ?>&raquo;?</p>
        <form action="" method="post">
            <input type = "submit" name = "del" value="Да" />
            <input type = "submit" name = "del" value="Нет" />
        </form>
    </div>
</div>