<?php $this->headTitle('Удаление пользователя'); ?>

<div id="strlist">
    <div class="strecord">
        <div class="theme">Удаление пользователя</div>
        <p>Вы действительно хотите удалить пользователя &laquo;<?php echo $this->user->username; ?>&raquo;?</p>
        <form action="" method="post">
            <input type = "submit" name = "del" value="Да" />
            <input type = "submit" name = "del" value="Нет" />
        </form>
    </div>
</div>