<?php $this->headTitle('Управление пользователями'); ?>

<div id="strlist">
    <div class="strecord">
        <div class="theme">Управление пользователями</div>
        <p><table>
        <tr>
        <th>Username</th>
        <th>Login</th>
        <th>Тип</th>
        <th>Дата регистрации</th>
        <th>Активность</th>
        <th></th>
        <th></th>
        </tr>
        <?php 
        $classTr = 'odd';
        foreach ($this->paginator as $user)
        { ?>
        <tr class="<?php echo $classTr ?>">
        <td><?php echo $user->username ?></td>
        <td><?php echo $user->login ?></td>
        <td><?php echo $user->user_type ?></td>
        <td><?php echo $this->dateTimeFormat($user->time_created) ?></td>
        <td><?php echo $this->dateTimeFormat($user->time_last) ?></td>
        <td><a href="<?php echo $this->url(array('module' => 'aria77',
                                                 'controller' => 'users',
                                                 'action' => 'edit',
                                                 'id' => $user->user_id),
                                           'editUser'); ?>">Edit</a></td>
            
        <?php if ($user->user_id != 1) : ?>
        <td><a href="<?php echo $this->url(array('module' => 'aria77',
                                                 'controller' => 'users',
                                                 'action' => 'delete',
                                                 'id' => $user->user_id),
                                          'deleteUser') ?>">Delete</a></td>
        <?php else : ?>
        <td>Delete</td>
        <?php endif; ?>
        </tr>
        <?php
            if ($classTr == 'odd') :
                $classTr = 'even';
            else :
                $classTr = 'odd';
            endif;
        } ?>
        </table></p>
    </div>
    <?php echo $this->paginationControl($this->paginator, 'Elastic', 'main_paginator.phtml'); ?>
</div>
