<?php if ($this->formValid) {
    $comment = $this->comment;
    $name = (!empty($comment->user_id)) ? $this->nameUser[$comment->user_id] : $comment->name;
    $link = 'none';
    if (!empty($comment->user_id)) {
        $link = $this->url(array('id' => $comment->user_id),'author');
    }
    if (!empty($comment->website)) {
        $link = $comment->website;
    }
    $time = $this->dateTimeFormat($comment->time_created);
    $text = $comment->text;
?>
{
    "result": 1,
    "name": "<?php echo $name; ?>",
    "link": "<?php echo $link; ?>",
    "time": "<?php echo $time; ?>",
    "text": "<?php echo $text; ?>"
}
<?php } else {
    echo $this->form;
} ?>
