<?php $this->headTitle('Восстановление пароля'); ?>

<div id="strlist">
<div class="strecord">
    <div class="theme">Восстановление пароля</div>
    <div class="strsigninform">
    <?php if (!empty($this->message)) { ?>
        <div class="messages">
            <?php foreach($this->message as $message) {
                    echo $message . '<br>';
                } ?>
        </div>
    <?php } ?>
    Введите email-адрес, указанный вами при регистрации.
    <?php echo $this->form; ?>
    </div>
</div>
</div>