<?php
    Zend_Loader::loadClass('My_TreeCategory');
    $tree = new My_TreeCategory;
    $child = $tree->child;
    
    function subCategory($childData, $allCategory, $child, $url)
    {
        $result = '<ul class="My_Navigation">' . PHP_EOL;
        foreach ($childData as $data) :
            if (!empty($allCategory[$data])) :
                $result .= '<li><a href="' . $url . '/category/' . $data . '/page/1">';
                $result .= $allCategory[$data]['name'] . '</a></li>' . PHP_EOL;
            endif;
            if (!empty($child[$data])) :
                $result .= subCategory($child[$data], $allCategory, $child, $url);
            endif;
        endforeach;
        $result .= '</ul>' . PHP_EOL;
        return $result;
    }
?>

<ul class="My_Navigation">
    <?php
    foreach ($this->allCategory as $key => $value) :
        if (empty($value['parent_id'])) :
            echo '<li><a href="' . $this->baseUrl . '/category/' . $key . '/page/1">';
            echo $value['name'] . '</a></li>' . PHP_EOL;
            if (!empty($child[$key])) :
                echo subCategory($child[$key], $this->allCategory, $child, $this->baseUrl);
            endif;
        endif;
    endforeach; ?>
</ul>