<?php if ($this->pageCount > 1): ?>
<div class="paginator">

<?php if (isset($this->previous)) : ?>
  <a href="<?php echo $this->url(array('page' => $this->previous)); ?>">
    &larr; Previous
	</a>
<?php endif; ?>
   |
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
    <a href="<?php echo $this->url(array('page' => $page)); ?>">
        <?php echo $page; ?>
    </a> |
  <?php else: ?>
    <?php echo $page; ?> |
  <?php endif; ?>
<?php endforeach; ?>
 
<?php if (isset($this->next)): ?>
  <a href="<?php echo $this->url(array('page' => $this->next)); ?>">
    Next &rarr;
  </a>
<?php endif; ?>
</div>
<?php endif; ?>