<?php echo $this->doctype(); ?>

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ru">
<head>
<?php
    $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8')
                     ->appendHttpEquiv('Content-Language', 'RU')
                     ->appendName('author', 'morontt');
    echo $this->headMeta() . PHP_EOL;
    echo $this->headTitle() . PHP_EOL;
    $this->headLink()->prependStylesheet('/css/main_s.css');
    $this->headLink(array('rel'  => 'shortcut icon',
                          'href' => '/favicon.ico',
                          'type' => 'image/x-icon'));
    echo $this->headLink() . PHP_EOL;
    echo $this->headScript() . PHP_EOL; ?>
</head>
<body>
    <div id="container">
        <div id="header">
            <div id="sitename">
                <a href="<?php
                            echo $this->url(array('page' => 1), 'home');
                         ?>"><?php echo $this->layout()->title; ?></a>
            </div>
        </div>
        <?php
            echo $this->siteMenu();
            echo $this->layout()->content;
		?>
        <div style="clear: both" />
        <div id="footer">
            &#169; 2011 <a href="<?php echo $this->url(array('page' => 1), 'home'); ?>"><?php echo $this->layout()->title; ?></a>: Footer
        </div>
    </div>
<script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-21476757-2']);
    _gaq.push(['_trackPageview']);
    (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
</script>
</body>
</html>
