<?php echo $this->doctype(); ?>

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ru">
<head>
<?php
    $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8')
                     ->appendHttpEquiv('Content-Language', 'RU')
                     ->appendName('author', 'morontt');
    echo $this->headMeta() . PHP_EOL;
    echo $this->headTitle() . PHP_EOL;
    $this->headLink()->prependStylesheet('/css/main_s.css');
    $this->headLink(array('rel'  => 'favicon',
                          'href' => '/img/favicon.ico',
                          'type' => 'image/x-icon'));
    echo $this->headLink() . PHP_EOL;
    echo $this->headScript() . PHP_EOL; ?>
</head>
<body>
    <div id="container">
        <div id="header">
            <div id="sitename">
                <a href="<?php
                            echo $this->url(array('page' => 1), 'home');
                         ?>"><?php echo $this->layout()->title; ?></a>
            </div>
        </div>
        <?php
            echo $this->siteMenu();
            echo $this->layout()->content;
		?>
        <div style="clear: both" />
        <div id="footer">
            &#169; 2011 <a href="<?php echo $this->url(array('page' => 1), 'home'); ?>"><?php echo $this->layout()->title; ?></a>: Footer
        </div>
    </div>
</body>
</html>
