<?php $this->headTitle('Удаление записи'); ?>

<div id="strlist">
    <div class="strecord">
        <div class="theme">Удаление записи</div>
        <p>Вы действительно хотите удалить запись &laquo;<?php echo $this->topic->title; ?>&raquo;?</p>
        <form action="" method="post">
            <input type = "submit" name = "del" value="Да" />
            <input type = "submit" name = "del" value="Нет" />
        </form>
    </div>
</div>