<?php $this->headTitle('Управление записями'); ?>

<div id="strlist">
    <div class="strecord">
        <div class="theme">Управление записями</div>
        <?php if (!empty($this->messages)) { ?>
        <div class="messages">
            <?php foreach($this->messages as $message) {
                    echo $message . '<br>';
                } ?>
        </div>
        <?php } ?>
        <p><table>
        <tr>
        <th>Заголовок</th>
        <th>Категория</th>
        <th>Скрытие</th>
        <th>Дата создания</th>
        <th></th>
        <th></th>
        </tr>
        <?php $classTr = 'odd';
        foreach ($this->paginator as $topic)
        { ?>
        <tr class="<?php echo $classTr; ?>">
        <td><?php echo $topic->title; ?></td>
        <td><?php echo $this->nameCategory[$topic->category_id]; ?></td>
        <?php if ($topic->hide) : ?>
        <td>Да</td>
        <?php else : ?>
        <td></td>
        <?php endif; ?>
        <td><?php echo $this->dateTimeFormat($topic->time_created); ?></td>
        <td><a href="<?php echo $this->url(array('module' => 'aria77',
                                                 'controller' => 'topic',
                                                 'action' => 'edit',
                                                 'id' => $topic->post_id),
                                             'editTopic');
                                            ?>">Edit</a></td>
        <td><a href="<?php echo $this->url(array('module' => 'aria77',
                                                 'controller' => 'topic',
                                                 'action' => 'delete',
                                                 'id' => $topic->post_id),
                                             'deleteTopic');
                                  ?>">Delete</a></td>
        </tr>
        <?php
            if ($classTr == 'odd') :
                $classTr = 'even';
            else :
                $classTr = 'odd';
            endif;
        } ?>
        </table></p>
        <p><a href="<?php echo $this->url(array('module' => 'aria77',
                                                'controller' => 'topic',
                                                'action' => 'add'),
                                            'addTopic');
                                            ?>" class="button">Создать новую запись</a></p>
    </div>
    <?php echo $this->paginationControl($this->paginator, 'Elastic', 'main_paginator.phtml'); ?>
</div>
