<?php $this->headTitle('Удаление категории'); ?>

<div id="strlist">
    <div class="strecord">
        <div class="theme">Удаление категории</div>
        
        <p>Вы действительно хотите удалить категорию &laquo;<?php echo $this->category->name; ?>&raquo;?</p>
        <form action="" method="post">
            <input type = "submit" name = "del" value="Да" />
            <input type = "submit" name = "del" value="Нет" />
        </form>       
    </div>
</div>